services:
  node0:
    container_name: node0
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node0:/tendermint
    command: node --proxy_app=kvstore

  node1:
    container_name: node1
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node1:/tendermint
    command: node --proxy_app=kvstore

  node2:
    container_name: node2
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node2:/tendermint
    command: node --proxy_app=kvstore

  node3:
    container_name: node3
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node3:/tendermint
    command: node --proxy_app=kvstore

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  tester:
    container_name: tester
    build: ./tester
    command: sleep infinity
    depends_on:
      - node0
      - node1
      - node2
      - node3
      - prometheus