services:
  node0:
    container_name: node0
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node0:/tendermint
    command: unsafe-reset-all

  node1:
    container_name: node1
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node1:/tendermint
    command: unsafe-reset-all

  node2:
    container_name: node2
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node2:/tendermint
    command: unsafe-reset-all

  node3:
    container_name: node3
    image: "tendermint/tendermint"
    volumes:
      - ./nodes/node3:/tendermint
    command: unsafe-reset-all