services:
  node0:
    container_name: node0
    image: "tendermint/tendermint"
    ports:
      - "26656-26657:26656-26657"
      - "26670:26660"
    volumes:
      - ./nodes/node0:/tendermint
    command: unsafe-reset-all

  node1:
    container_name: node1
    image: "tendermint/tendermint"
    ports:
      - "26659-26660:26656-26657"
      - "26671:26660"
    volumes:
      - ./nodes/node1:/tendermint
    command: unsafe-reset-all

  node2:
    container_name: node2
    image: "tendermint/tendermint"
    ports:
      - "26661-26662:26656-26657"
      - "26672:26660"
    volumes:
      - ./nodes/node2:/tendermint
    command: unsafe-reset-all

  node3:
    container_name: node3
    image: "tendermint/tendermint"
    ports:
      - "26663-26664:26656-26657"
      - "26673:26660"
    volumes:
      - ./nodes/node3:/tendermint
    command: unsafe-reset-all